export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const SET_IS_FILTERED = 'SET_IS_FILTERED';
export const SET_FILTER_BY = 'SET_FILTER_BY';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';

export const SET_CART = 'SET_CART';
export const SET_LOADING_CART = 'SET_LOADING_CART';

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_LOADING_TRANSACTIONS = 'SET_LOADING_TRANSACTIONS';